# Generated by Django 5.0.4 on 2024-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={},
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
