# Generated by Django 5.0.4 on 2024-05-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_topics'),
        ('topic', '0002_topic_created_by_topic_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.course'),
        ),
    ]
