# Generated by Django 5.0.4 on 2024-05-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_alter_topic_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
