from typing import Any


class BaseStorage:
    name: Any
    read_mode: Any
    encoding: Any
    def __init__(self, name: Any | None = ..., read_mode: str = ..., encoding: Any | None = ...) -> None: ...
    def save(self, data: Any) -> None: ...
    def read(self) -> None: ...
    def remove(self) -> None: ...

class TempFolderStorage(BaseStorage):
    def save(self, data: Any) -> None: ...
    def read(self) -> Any: ...
    def remove(self) -> None: ...
    def get_full_path(self) -> Any: ...

class CacheStorage(BaseStorage):
    CACHE_LIFETIME: int
    CACHE_PREFIX: str
    name: Any
    def save(self, data: Any) -> None: ...
    def read(self) -> Any: ...
    def remove(self) -> None: ...

class MediaStorage(BaseStorage):
    MEDIA_FOLDER: str
    def __init__(self, name: Any | None = ..., read_mode: str = ..., encoding: Any | None = ...) -> None: ...
    name: Any
    def save(self, data: Any) -> None: ...
    def read(self) -> Any: ...
    def remove(self) -> None: ...
    def get_full_path(self) -> Any: ...
