from typing import Any


class atomic_if_using_transaction:
    using_transactions: Any
    context_manager: Any
    def __init__(self, using_transactions: Any, using: Any) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...

def original(method: Any) -> Any: ...
