from typing import Any

class Format:
    def get_title(self) -> Any: ...
    def create_dataset(self, in_stream: Any) -> None: ...
    def export_data(self, dataset: Any, escape_output: bool = ..., **kwargs: Any) -> None: ...
    def is_binary(self) -> Any: ...
    def get_read_mode(self) -> Any: ...
    def get_extension(self) -> Any: ...
    def get_content_type(self) -> Any: ...
    @classmethod
    def is_available(cls) -> Any: ...
    def can_import(self) -> Any: ...
    def can_export(self) -> Any: ...

class TablibFormat(Format):
    TABLIB_MODULE: Any
    CONTENT_TYPE: str
    encoding: Any
    def __init__(self, encoding: Any | None = ...) -> None: ...
    def get_format(self) -> Any: ...
    @classmethod
    def is_available(cls) -> Any: ...
    def get_title(self) -> Any: ...
    def create_dataset(self, in_stream: Any, **kwargs: Any) -> Any: ...
    def export_data(self, dataset: Any, escape_output: bool = ..., **kwargs: Any) -> None: ...
    def get_extension(self) -> Any: ...
    def get_content_type(self) -> Any: ...
    def can_import(self) -> Any: ...
    def can_export(self) -> Any: ...

class TextFormat(TablibFormat):
    def create_dataset(self, in_stream: Any, **kwargs: Any) -> Any: ...
    def get_read_mode(self) -> Any: ...
    def is_binary(self) -> Any: ...

class CSV(TextFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str

class JSON(TextFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str

class YAML(TextFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str

class TSV(TextFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str
    def create_dataset(self, in_stream: Any, **kwargs: Any) -> Any: ...

class ODS(TextFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str

class HTML(TextFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str
    def export_data(self, dataset: Any, escape_output: bool = ..., **kwargs: Any) -> Any: ...

class XLS(TablibFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str
    def create_dataset(self, in_stream: Any, **kwargs: Any) -> Any: ...

class XLSX(TablibFormat):
    TABLIB_MODULE: str
    CONTENT_TYPE: str
    def create_dataset(self, in_stream: Any, **kwargs: Any) -> Any: ...

DEFAULT_FORMATS: Any
