# Generated by Django 5.0.4 on 2024-04-17 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object creation datetime.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated datetime.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates this object as soft deleted.', verbose_name='deleted status')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('title_el', models.CharField(max_length=255, null=True)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_hr', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_el', models.TextField(null=True)),
                ('description_pt', models.TextField(null=True)),
                ('description_hr', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('is_visible', models.BooleanField(default=False, help_text='Designates this object as being visible', verbose_name='visibility status')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
