# Generated by Django 5.0.4 on 2024-04-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsmodel',
            options={'verbose_name_plural': 'Job Details'},
        ),
    ]
