# Generated by Django 5.0.4 on 2024-04-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsmodel',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Job Details'},
        ),
    ]
