# Generated by Django 5.0.4 on 2024-05-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_enrollmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='topics',
        ),
    ]
